#pragma once

#define		FACE_DETECT_ID			"DllFD11"
#define		AGE_ESTIMATION_ID		"DllAE11"
#define		GENDER_ESTIMATION_ID	"DllGE11"
#define		HEAD_POSTION_ID			"DllHP11"
#define		EYE_WINK_ID				"DllEW11"

#define		FACE_DETECT_KEY			"7BH74-RD31J-LE1LU-G8U52"
#define		AGE_ESTIMATION_KEY		"7BH74-RRZFW-17DXB-LWRQ1"
#define		GENDER_ESTIMATION_KEY	"7BH74-R9Z1G-LAHK6-PWUK2"
#define		HEAD_POSTION_KEY		"7BH74-R939R-9EPRA-5LEP2"
#define		EYE_WINK_KEY			"7BH74-R1ZXQ-HUU8B-PX7J2"
